"""
Phase 4 - Statistical Analysis
------------------------------
Reads the DuckDB warehouse and answers five questions:
  A. How much did the Medicare behavioral-health workforce change? (like-for-like)
  B. Is provider supply related to unmet need / counseling received? (Spearman)
  C. Is the Access Gap Score robust to weighting choices? (sensitivity analysis)
  D. Do states that pay more retain more providers? (Spearman)
  E. Which providers bill far outside their peers? (robust z-score outliers)
  F. Who has the most unmet need? (demographic breakdowns)

Outputs:
  docs/analysis_findings.md        auto-generated findings with real numbers
  docs/figures/*.png               charts for the README
  tableau/data/analysis_*.csv      extra tables for the dashboard

Usage:
    python src/analyze.py
"""
from pathlib import Path

import duckdb
import matplotlib
import numpy as np
import pandas as pd
from scipy import stats

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "warehouse.duckdb"
FIG = ROOT / "docs" / "figures"
EXPORT = ROOT / "tableau" / "data"
REPORT = ROOT / "docs" / "analysis_findings.md"
FIG.mkdir(parents=True, exist_ok=True)

con = duckdb.connect(str(DB), read_only=True)
q = lambda sql: con.execute(sql).df()  # noqa: E731
md: list[str] = ["# Analysis Findings\n",
                 "_Auto-generated by `src/analyze.py` from the DuckDB warehouse._\n"]


def say(text: str = "") -> None:
    print(text)
    md.append(text)


def spearman(x: pd.Series, y: pd.Series) -> tuple[float, float, int]:
    mask = x.notna() & y.notna()
    rho, p = stats.spearmanr(x[mask], y[mask])
    return float(rho), float(p), int(mask.sum())


def describe_corr(rho: float, p: float) -> str:
    strength = ("negligible" if abs(rho) < 0.1 else "weak" if abs(rho) < 0.3
                else "moderate" if abs(rho) < 0.5 else "strong")
    direction = "positive" if rho > 0 else "negative"
    sig = "statistically significant" if p < 0.05 else "not statistically significant"
    return f"{strength} {direction} (rho = {rho:.2f}, p = {p:.3f}, {sig} at 0.05)"


def pct_rank(s: pd.Series, ascending: bool = True) -> pd.Series:
    """Same definition as SQL PERCENT_RANK(): (rank - 1) / (n - 1)."""
    r = s.rank(method="min", ascending=ascending)
    return (r - 1) / (s.notna().sum() - 1)


# ===================================================================== A
say("## A. Workforce change, 2019 to 2024\n")
cat = q("SELECT * FROM mart_category_trend ORDER BY bh_category, year")
kpi = q("SELECT * FROM mart_national_kpis ORDER BY year")

p19 = cat.query("year == 2019").set_index("bh_category")["providers"]
p24 = cat.query("year == 2024").set_index("bh_category")["providers"]
legacy = [c for c in p19.index if p19[c] > 0]
lfl19, lfl24 = p19[legacy].sum(), p24[legacy].sum()

say(f"- All BH providers: {int(kpi.bh_providers.iloc[0]):,} (2019) to "
    f"{int(kpi.bh_providers.iloc[-1]):,} (2024), "
    f"{100 * (kpi.bh_providers.iloc[-1] / kpi.bh_providers.iloc[0] - 1):+.1f}%")
say(f"- Like-for-like (excluding Counselor / MFT, newly eligible in 2024): "
    f"{int(lfl19):,} to {int(lfl24):,}, {100 * (lfl24 / lfl19 - 1):+.1f}%")
say(f"- Total Medicare BH payment: ${kpi.payment_amt.iloc[0] / 1e9:.2f}B to "
    f"${kpi.payment_amt.iloc[-1] / 1e9:.2f}B; payment per service "
    f"${kpi.payment_per_service.iloc[0]:.2f} to ${kpi.payment_per_service.iloc[-1]:.2f}\n")

say("| Category | 2019 | 2024 | Change | CAGR |")
say("|---|---:|---:|---:|---:|")
for c in legacy:
    cagr = (p24[c] / p19[c]) ** (1 / 5) - 1
    say(f"| {c} | {int(p19[c]):,} | {int(p24[c]):,} | {100 * (p24[c] / p19[c] - 1):+.1f}% "
        f"| {100 * cagr:+.1f}%/yr |")

fig, ax = plt.subplots(figsize=(8, 4.5))
for c in legacy:
    s = cat[cat.bh_category == c]
    ax.plot(s.year, 100 * s.providers / s.providers.iloc[0], marker="o", label=c)
ax.axhline(100, color="grey", lw=0.8, ls="--")
ax.set(title="Medicare behavioral-health providers (2019 = 100)",
       xlabel="", ylabel="Index")
ax.legend(frameon=False)
fig.tight_layout()
fig.savefig(FIG / "workforce_index.png", dpi=150)
plt.close(fig)

# ===================================================================== B
say("\n## B. Is provider supply related to mental-health outcomes?\n")
gap = q("SELECT * FROM mart_state_gap")
rho, p, n = spearman(gap.providers_per_100k_2020_22, gap.unmet_need_pct)
say(f"- Providers per 100k vs **unmet counseling need** (n={n}): {describe_corr(rho, p)}")
rho2, p2, _ = spearman(gap.providers_per_100k_2020_22, gap.received_counseling_pct)
say(f"- Providers per 100k vs **received counseling**: {describe_corr(rho2, p2)}")
say("- Interpretation: correlation across 51 states is descriptive, not causal. "
    "Medicare billing covers only part of each state's mental-health workforce.")

fig, ax = plt.subplots(figsize=(8, 6))
top = gap.nsmallest(10, "access_gap_rank")
ax.scatter(gap.providers_per_100k_2020_22, gap.unmet_need_pct, alpha=0.6)
ax.scatter(top.providers_per_100k_2020_22, top.unmet_need_pct, color="crimson",
           label="Top 10 access gap")
for _, r in gap.iterrows():
    ax.annotate(r.state, (r.providers_per_100k_2020_22, r.unmet_need_pct),
                fontsize=7, xytext=(3, 2), textcoords="offset points")
ax.axvline(gap.providers_per_100k_2020_22.median(), color="grey", lw=0.8, ls="--")
ax.axhline(gap.unmet_need_pct.median(), color="grey", lw=0.8, ls="--")
ax.set(title="Unmet counseling need vs Medicare BH provider supply (2020-22)",
       xlabel="BH providers billing Medicare per 100k residents",
       ylabel="Adults with unmet counseling need (%)")
ax.legend(frameon=False, loc="upper right")
fig.tight_layout()
fig.savefig(FIG / "gap_scatter.png", dpi=150)
plt.close(fig)

# ===================================================================== C
say("\n## C. Sensitivity of the Access Gap Score\n")
scenarios = {
    "base_50_50":        (0.5, "providers_per_100k_2020_22"),
    "demand_heavy_70_30": (0.7, "providers_per_100k_2020_22"),
    "supply_heavy_30_70": (0.3, "providers_per_100k_2020_22"),
    "current_supply_2024": (0.5, "providers_per_100k_2024"),
}
sens = gap[["state", "state_name"]].copy()
for name, (w, col) in scenarios.items():
    sens[name] = 100 * (w * pct_rank(gap.unmet_need_pct)
                        + (1 - w) * pct_rank(gap[col], ascending=False))

base_top = set(sens.nlargest(10, "base_50_50").state)
say("| Scenario | Top-10 overlap with base | Rank correlation with base |")
say("|---|---:|---:|")
in_all = base_top.copy()
for name in scenarios:
    top10 = set(sens.nlargest(10, name).state)
    in_all &= top10
    r, _ = stats.spearmanr(sens.base_50_50, sens[name])
    say(f"| {name} | {len(base_top & top10)}/10 | {r:.2f} |")
sens["top10_in_all_scenarios"] = sens.state.isin(in_all)
say(f"\n- States in the top 10 under **every** scenario (most robust findings): "
    f"**{', '.join(sorted(in_all)) or 'none'}**")
sens.to_csv(EXPORT / "analysis_gap_sensitivity.csv", index=False)

# ===================================================================== D
say("\n## D. Do higher-paying states retain more providers?\n")
change = q("""
    SELECT state,
           sum(providers) FILTER (WHERE year = 2019) AS p2019,
           sum(providers) FILTER (WHERE year = 2024 AND bh_category <> 'Counselor / MFT') AS p2024_lfl
    FROM fct_state_supply GROUP BY state""")
change["lfl_change_pct"] = 100 * (change.p2024_lfl / change.p2019 - 1)
d = gap[["state", "psychotherapy_payment_index"]].merge(change, on="state")
rho3, p3, n3 = spearman(d.psychotherapy_payment_index, d.lfl_change_pct)
say(f"- 90837 payment index vs like-for-like provider change (n={n3}): {describe_corr(rho3, p3)}")
say(f"- Largest declines: " + ", ".join(
    f"{r.state} ({r.lfl_change_pct:+.0f}%)" for r in d.nsmallest(5, "lfl_change_pct").itertuples()))
say(f"- Smallest declines / growth: " + ", ".join(
    f"{r.state} ({r.lfl_change_pct:+.0f}%)" for r in d.nlargest(5, "lfl_change_pct").itertuples()))
d.to_csv(EXPORT / "analysis_state_change.csv", index=False)

fig, ax = plt.subplots(figsize=(8, 5))
ax.scatter(d.psychotherapy_payment_index, d.lfl_change_pct, alpha=0.7)
for r in d.itertuples():
    ax.annotate(r.state, (r.psychotherapy_payment_index, r.lfl_change_pct),
                fontsize=7, xytext=(3, 2), textcoords="offset points")
ax.axvline(1.0, color="grey", lw=0.8, ls="--")
ax.axhline(0, color="grey", lw=0.8, ls="--")
ax.set(title="Medicare psychotherapy rates vs provider retention",
       xlabel="60-min psychotherapy payment vs national (1.0 = national avg, 2024)",
       ylabel="Like-for-like provider change 2019-24 (%)")
fig.tight_layout()
fig.savefig(FIG / "reimbursement_vs_retention.png", dpi=150)
plt.close(fig)

# ===================================================================== E
say("\n## E. Billing outliers (2024, robust z-score within provider type)\n")
prov = q("""SELECT npi, provider_type, bh_category, state, tot_benes, tot_services,
                   tot_payment_amt, payment_per_service
            FROM mart_provider_detail
            WHERE year = 2024 AND tot_services > 0 AND tot_payment_amt > 0""")
prov["services_per_bene"] = prov.tot_services / prov.tot_benes


def robust_z(s: pd.Series) -> pd.Series:
    x = np.log(s)
    med = x.median()
    mad = (x - med).abs().median()
    return 0.6745 * (x - med) / mad if mad > 0 else pd.Series(0.0, index=s.index)


for metric in ["payment_per_service", "services_per_bene"]:
    prov[f"z_{metric}"] = prov.groupby("provider_type")[metric].transform(robust_z)
prov["is_outlier"] = (prov.z_payment_per_service.abs() > 3.5) | (prov.z_services_per_bene.abs() > 3.5)

say(f"- Method: log-transform, then median/MAD z-score per provider type; |z| > 3.5 flagged "
    "(Iglewicz & Hoaglin). Robust to the skew that breaks mean/std z-scores.")
say(f"- Flagged {int(prov.is_outlier.sum()):,} of {len(prov):,} providers "
    f"({100 * prov.is_outlier.mean():.2f}%)\n")
say("| Category | Providers | Flagged | % |")
say("|---|---:|---:|---:|")
for c, g in prov.groupby("bh_category"):
    say(f"| {c} | {len(g):,} | {int(g.is_outlier.sum()):,} | {100 * g.is_outlier.mean():.2f}% |")
say("\n- These are statistical outliers for review, **not** evidence of fraud: case mix, "
    "facility billing and group practices can all explain unusual patterns.")
prov[prov.is_outlier].sort_values("z_payment_per_service", key=abs, ascending=False) \
    .to_csv(EXPORT / "analysis_provider_outliers.csv", index=False)

# ===================================================================== F
say("\n## F. Who has the most unmet need? (CDC, Aug 2020 - May 2022)\n")
grp = q("SELECT * FROM mart_demand_by_group")
for g in sorted(grp.group_name.unique()):
    if g == "National Estimate":
        continue
    piv = grp[grp.group_name == g].pivot_table(index="subgroup", columns="indicator",
                                               values="avg_pct")
    if "Unmet Counseling Need" not in piv:
        continue
    piv = piv.sort_values("Unmet Counseling Need", ascending=False)
    hi, lo = piv.index[0], piv.index[-1]
    say(f"- **{g}**: highest unmet need = {hi} ({piv.iloc[0]['Unmet Counseling Need']:.1f}%), "
        f"lowest = {lo} ({piv.iloc[-1]['Unmet Counseling Need']:.1f}%)")

REPORT.write_text("\n".join(md))
print(f"\nFindings: {REPORT}\nFigures:  {FIG}\nExports:  {EXPORT}/analysis_*.csv")